#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
ROOT_PATH="$DIR/../"
for module in 1 2 3 4 5
do
    echo "- Removing files from module ${module}"
    CDKRoot=$ROOT_PATH/module-$module/cdk
    AppFiles=$CDKRoot/bin/*.js
    cd $CDKRoot
    for app in $AppFiles
    do
        appFile="$(basename -- $app)"
        echo "  : Removing stack generated by $appFile"
        # cdk destroy $appFile
    done
done